name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: npm install
        uses: actions/npm@main
        with:
          args: install
      # - name: npm test
      #   uses: actions/npm@master
      #   with:
      #     args: run test
      - name: npm lint
        uses: actions/npm@main
        with:
          args: run lint